### ISSUE TITLE
 Uncaught TypeError: str_pad() expects parameter 1 to be string, bool given 

### ISSUE THREAD

**Issue by gadget00** [luads/php-xbase#114]
Hi all,

after upgrading to 1.4.0 to try to fix the other issue I mentioned before, now I get this TypeError when I do the writeRecord() after appending a new record and filling out the data in the fields:

```
PHP Fatal error:  Uncaught TypeError: str_pad() expects parameter 1 to be string, bool given in C:\inetpub\wwwroot\app\vendor\hisamu\php-xbase\src\XBase\DataConverter\Field\DBase\StringConverter.php:30
Stack trace:
#0 C:\inetpub\wwwroot\app\vendor\hisamu\php-xbase\src\XBase\DataConverter\Field\DBase\StringConverter.php(30): str_pad()
#1 C:\inetpub\wwwroot\app\vendor\hisamu\php-xbase\src\XBase\DataConverter\Record\DBaseDataConverter.php(107): XBase\DataConverter\Field\DBase\StringConverter->toBinaryString()
#2 C:\inetpub\wwwroot\app\vendor\hisamu\php-xbase\src\XBase\DataConverter\Record\DBaseDataConverter.php(72): XBase\DataConverter\Record\DBaseDataConverter->denormalizeField()
#3 C:\inetpub\wwwroot\app\vendor\hisamu\php-xbase\src\XBase\WritableTable.php(251): XBase\DataConverter\Record\DBaseDataConverter->toBinaryString()
#4 C:\inetpub\wwwroot\app\data\guardar_nuevo_cliente.php(228): XBase\WritableTable->writeRecord()
#5 C:\inetpub\wwwroot\app\actualizar_cliente_c in C:\inetpub\wwwroot\antiblanqueo\vendor\hisamu\php-xbase\src\XBase\DataConverter\Field\DBase\StringConverter.php on line 30
```

I hope you can give me some help; It's become a critical issue for us not been able to insert correctly in the DBF

**Comment by gam6itko** [comment]
Is the issue actual for file from #133 ?
Can you provide some code to speed up fixing the issue?
